#!/bin/bash

echo "Running custom build hook"

echo "SOURCE_BRANCH: $SOURCE_BRANCH"
echo "SOURCE_COMMIT: $SOURCE_COMMIT"
echo "DOCKERFILE_PATH: $DOCKERFILE_PATH"
echo "DOCKER_REPO: $DOCKER_REPO"
echo "CACHE_TAG: $CACHE_TAG"
echo "IMAGE_NAME: $IMAGE_NAME"

SOURCE_DATE=$(git log -n1 --date=iso-strict | grep 'Date:' | sed 's|Date:\s*||g')

docker build \
    --build-arg SOURCE_BRANCH=$SOURCE_BRANCH \
    --build-arg SOURCE_COMMIT=$SOURCE_COMMIT \
    --build-arg SOURCE_DATE=$SOURCE_DATE \
    -f $DOCKERFILE_PATH \
    -t $IMAGE_NAME \
    .
