#!/usr/bin/env sh

echo "Running custom build hook"

echo "SOURCE_BRANCH: $SOURCE_BRANCH"
echo "SOURCE_COMMIT: $SOURCE_COMMIT"
echo "DOCKERFILE_PATH: $DOCKERFILE_PATH"
echo "DOCKER_REPO: $DOCKER_REPO"
echo "CACHE_TAG: $CACHE_TAG"
echo "IMAGE_NAME: $IMAGE_NAME"

# if running from master check if the source commit is not referenced in known tags
# if that's the case use the last tag rather than 'master'
# this is because SOURCE_BRANCH is later injected into migrator.go and used as a version identifier
# a little bit more user friendly than master and commit sha/date
if [[ "$SOURCE_BRANCH" == "master" ]]; then
  TAGS=$(git tag --contains $SOURCE_COMMIT 2> /dev/null)
  if [[ $? -eq 0 ]]; then
    SOURCE_BRANCH=$(echo "$TAGS" | tail -1)
    echo "Changed master to $SOURCE_BRANCH"
  fi
fi

docker build --build-arg SOURCE_BRANCH=$SOURCE_BRANCH -f $DOCKERFILE_PATH -t $IMAGE_NAME .
