#!/bin/bash

echo "Running custom post_push hook"

echo "SOURCE_BRANCH: $SOURCE_BRANCH"
echo "SOURCE_COMMIT: $SOURCE_COMMIT"
echo "DOCKERFILE_PATH: $DOCKERFILE_PATH"
echo "DOCKER_REPO: $DOCKER_REPO"
echo "CACHE_TAG: $CACHE_TAG"
echo "IMAGE_NAME: $IMAGE_NAME"

# if running from dev-* branch don't push to latest tag
if [[ $SOURCE_BRANCH != dev-* ]]; then
    echo "Pushing $IMAGE_NAME to latest"
    docker tag $IMAGE_NAME $DOCKER_REPO:latest
    docker push $DOCKER_REPO:$latest
else
    echo "Detected dev branch, not pushing $IMAGE_NAME to latest"
fi
