name: Build and test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    strategy:
      matrix:
        go: [ '1.17', '1.16', '1.15' ]
    name: Go ${{ matrix.go }}

    steps:
    - uses: actions/checkout@v5

    - name: Setup Go
      uses: actions/setup-go@v6
      with:
        go-version: ${{ matrix.go }}

    - name: Run staticcheck (only latest go version)
      if: matrix.go == '1.17'
      run: ./staticcheck.sh

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Start docker-compose services
      run: docker-compose -f test/docker-compose-it.yaml up -d

    - name: Build and test migrator
      env:
        AZURE_STORAGE_ACCESS_KEY: ${{ secrets.AZURE_STORAGE_ACCESS_KEY }}
        AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
      run: ./coverage.sh

    - name: Run HTTP integration tests
      run: ./test/http-integration-tests.sh

    - uses: codecov/codecov-action@v5.5.1
